jwt.key.secret=V0Jhc285Zk1oZTFxVG5Hc29pR1NPbWxKNWhUdkdCZGw=
jwt.expiration_time=86400000

upload.base.path=D:/upload
upload.broker.path=/broker

batch.job.base.path=D:/upload/batchjob
batch.job.done.path=D:/upload/batchjob/done
batch.job.wait.path=D:/upload/batchjob/wait
batch.job.ready.path=D:/upload/batchjob/ready

