jwt.key.secret=V0Jhc285Zk1oZTFxVG5Hc29pR1NPbWxKNWhUdkdCZGw=
jwt.expiration_time=86400000

upload.base.path=/home/dojun8ho/upload
upload.broker.path=/broker

batch.job.base.path=/home/dojun8ho/upload/batchjob
batch.job.done.path=/home/dojun8ho/upload/batchjob/done