log4jdbc.spylogdelegator.name=homes.log.HomesSpyLogDelegator
log4jdbc.dump.sql.maxlinelength=0
log4jdbc.dump.sql.select=true
log4jdbc.dump.sql.insert=true
log4jdbc.dump.sql.update=true
log4jdbc.dump.sql.delete=true
log4jdbc.dump.sql.addsemicolon=false
log4jdbc.dump.sql.trim.sql=true
log4jdbc.dump.sql.executionTime=true
log4jdbc.dump.sql.multiline=true
log4jdbc.auto.load.popular.drivers=false